# Generated by Django 4.1.1 on 2022-09-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursechapter',
            old_name='name',
            new_name='chepter_name',
        ),
    ]
