# Generated by Django 4.1.1 on 2022-09-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_coursechapter_chepter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='chepter_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
