# Generated by Django 4.1.1 on 2022-09-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_coursechapter_chepter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='asi_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coursechapter',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursechapter',
            old_name='chepter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='coursechapter',
            old_name='chepter_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('UNKNOWN', 'Unknown')], max_length=10),
        ),
    ]
