# Generated by Django 4.1.1 on 2022-09-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_asi_id_assignment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
    ]
